name: Frontend Test

on:
  push:
    branches:
      - main
      - "release/v*.*.*"
  pull_request:
    branches: [main]
    paths:
      - "frontend/web/**"

jobs:
  eslint-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: pnpm
          cache-dependency-path: "frontend/web/pnpm-lock.yaml"
      - run: pnpm install
        working-directory: frontend/web
      - name: Run eslint check
        run: pnpm lint
        working-directory: frontend/web
      - name: Run type check
        run: pnpm type-check
        working-directory: frontend/web

  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 10
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: pnpm
          cache-dependency-path: "frontend/web/pnpm-lock.yaml"
      - run: pnpm install
        working-directory: frontend/web
      - name: Run frontend build
        run: pnpm build
        working-directory: frontend/web
